spring.application.name=TravelApp

spring.datasource.url=jdbc:postgresql://localhost:5432/travel
spring.datasource.username=postgres
spring.datasource.password=invatdb

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
